### ISSUE TITLE
replace eio with Dataset object

### ISSUE THREAD

**Issue by hackalog** [acwooding/dimension_reduction#50]
Use dataset objects (Bunch) for all experiments

Add an `experiment` dictionary to the dset metadata:
```
{
    experiment_name:
    run_no:
    start_time / end_time
    desc:
    alg_func
    alg_args
}
```

Create save and load functions to Dataset object 
Add `dataset_name` to dset object

**Comment by hackalog** [comment]
general idea
```
dataset_out = run_experiment(dataset_in, alg_w_flags, experiment_dict, force=False)
```

**Comment by acwooding** [comment]
Most of this work is in #52, and the additional updates to notebooks in #53. I think we can completely remove embedding_io.py at this point.
