### ISSUE TITLE
Changed parameters for synthetic dataset, but load_dataset did not regenerate the dataset with new parameters

### ISSUE THREAD

**Issue by acwooding** [acwooding/dimension_reduction#71]
As in title. It only regenerated the dataset (with the new parameters) once `force=True` was passed into `load_dataset`

This was with `twinpeaks` and the parameter that was changed was n_points

**Comment by hackalog** [comment]
I think this was `twinpeaks` with changing `n_points`

**Comment by hackalog** [comment]
I can't reproduce this. It totally looks like it works as expected. Re-open if you experience it again
